// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/commands.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 2. Команда: Калькулятор
type Operation int32

const (
	Operation_ADD      Operation = 0 // Сложение
	Operation_MULTIPLY Operation = 1 // Умножение
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "ADD",
		1: "MULTIPLY",
	}
	Operation_value = map[string]int32{
		"ADD":      0,
		"MULTIPLY": 1,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_commands_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_commands_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{0}
}

// 1. Команда: Получить время
type TimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRequest) Reset() {
	*x = TimeRequest{}
	mi := &file_proto_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRequest) ProtoMessage() {}

func (x *TimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRequest.ProtoReflect.Descriptor instead.
func (*TimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{0}
}

type TimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentTime   string                 `protobuf:"bytes,1,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeResponse) Reset() {
	*x = TimeResponse{}
	mi := &file_proto_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeResponse) ProtoMessage() {}

func (x *TimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeResponse.ProtoReflect.Descriptor instead.
func (*TimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{1}
}

func (x *TimeResponse) GetCurrentTime() string {
	if x != nil {
		return x.CurrentTime
	}
	return ""
}

type CalcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             float64                `protobuf:"fixed64,1,opt,name=a,proto3" json:"a,omitempty"`
	B             float64                `protobuf:"fixed64,2,opt,name=b,proto3" json:"b,omitempty"`
	Op            Operation              `protobuf:"varint,3,opt,name=op,proto3,enum=commands.Operation" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	mi := &file_proto_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{2}
}

func (x *CalcRequest) GetA() float64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *CalcRequest) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *CalcRequest) GetOp() Operation {
	if x != nil {
		return x.Op
	}
	return Operation_ADD
}

type CalcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcResponse) Reset() {
	*x = CalcResponse{}
	mi := &file_proto_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcResponse) ProtoMessage() {}

func (x *CalcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcResponse.ProtoReflect.Descriptor instead.
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{3}
}

func (x *CalcResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 3. Команда: Обработка текста
type TextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextRequest) Reset() {
	*x = TextRequest{}
	mi := &file_proto_commands_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextRequest) ProtoMessage() {}

func (x *TextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextRequest.ProtoReflect.Descriptor instead.
func (*TextRequest) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{4}
}

func (x *TextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessedText string                 `protobuf:"bytes,1,opt,name=processed_text,json=processedText,proto3" json:"processed_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_proto_commands_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_commands_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_proto_commands_proto_rawDescGZIP(), []int{5}
}

func (x *TextResponse) GetProcessedText() string {
	if x != nil {
		return x.ProcessedText
	}
	return ""
}

var File_proto_commands_proto protoreflect.FileDescriptor

const file_proto_commands_proto_rawDesc = "" +
	"\n" +
	"\x14proto/commands.proto\x12\bcommands\"\r\n" +
	"\vTimeRequest\"1\n" +
	"\fTimeResponse\x12!\n" +
	"\fcurrent_time\x18\x01 \x01(\tR\vcurrentTime\"N\n" +
	"\vCalcRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x01R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x01R\x01b\x12#\n" +
	"\x02op\x18\x03 \x01(\x0e2\x13.commands.OperationR\x02op\"&\n" +
	"\fCalcResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result\"!\n" +
	"\vTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"5\n" +
	"\fTextResponse\x12%\n" +
	"\x0eprocessed_text\x18\x01 \x01(\tR\rprocessedText*\"\n" +
	"\tOperation\x12\a\n" +
	"\x03ADD\x10\x00\x12\f\n" +
	"\bMULTIPLY\x10\x012\xc4\x01\n" +
	"\x0eCommandService\x128\n" +
	"\aGetTime\x12\x15.commands.TimeRequest\x1a\x16.commands.TimeResponse\x12:\n" +
	"\tCalculate\x12\x15.commands.CalcRequest\x1a\x16.commands.CalcResponse\x12<\n" +
	"\vProcessText\x12\x15.commands.TextRequest\x1a\x16.commands.TextResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_commands_proto_rawDescOnce sync.Once
	file_proto_commands_proto_rawDescData []byte
)

func file_proto_commands_proto_rawDescGZIP() []byte {
	file_proto_commands_proto_rawDescOnce.Do(func() {
		file_proto_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_commands_proto_rawDesc), len(file_proto_commands_proto_rawDesc)))
	})
	return file_proto_commands_proto_rawDescData
}

var file_proto_commands_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_commands_proto_goTypes = []any{
	(Operation)(0),       // 0: commands.Operation
	(*TimeRequest)(nil),  // 1: commands.TimeRequest
	(*TimeResponse)(nil), // 2: commands.TimeResponse
	(*CalcRequest)(nil),  // 3: commands.CalcRequest
	(*CalcResponse)(nil), // 4: commands.CalcResponse
	(*TextRequest)(nil),  // 5: commands.TextRequest
	(*TextResponse)(nil), // 6: commands.TextResponse
}
var file_proto_commands_proto_depIdxs = []int32{
	0, // 0: commands.CalcRequest.op:type_name -> commands.Operation
	1, // 1: commands.CommandService.GetTime:input_type -> commands.TimeRequest
	3, // 2: commands.CommandService.Calculate:input_type -> commands.CalcRequest
	5, // 3: commands.CommandService.ProcessText:input_type -> commands.TextRequest
	2, // 4: commands.CommandService.GetTime:output_type -> commands.TimeResponse
	4, // 5: commands.CommandService.Calculate:output_type -> commands.CalcResponse
	6, // 6: commands.CommandService.ProcessText:output_type -> commands.TextResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_commands_proto_init() }
func file_proto_commands_proto_init() {
	if File_proto_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_commands_proto_rawDesc), len(file_proto_commands_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_commands_proto_goTypes,
		DependencyIndexes: file_proto_commands_proto_depIdxs,
		EnumInfos:         file_proto_commands_proto_enumTypes,
		MessageInfos:      file_proto_commands_proto_msgTypes,
	}.Build()
	File_proto_commands_proto = out.File
	file_proto_commands_proto_goTypes = nil
	file_proto_commands_proto_depIdxs = nil
}
